services:
    database:
        image: postgres:18
        restart: unless-stopped

        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

        ports:
            - "${POSTGRES_PORT}:5432"

        volumes:
            - database_data:/var/lib/postgresql

volumes:
    database_data:
