services:
    database:
        image: postgres:18

        container_name: database

        restart: unless-stopped

        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

        ports:
            - "127.0.0.1:${POSTGRES_PORT}:5432"

        volumes:
            - database_data:/var/lib/postgresql
            - ./back_end/init_db:/docker-entrypoint-initdb.d:ro

        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
                ]
            interval: 5s
            timeout: 5s
            retries: 10

    collector_licitacao:
        build:
            context: ./collector
            dockerfile: Dockerfile

        container_name: collectorLicit

        restart: "no"

        env_file:
            - .env

        command: ["python", "main_licitacao.py"]

        depends_on:
            database:
                condition: service_healthy

    collector_dispensa:
        build:
            context: ./collector
            dockerfile: Dockerfile

        container_name: collectorDisp

        restart: "no"

        env_file:
            -   .env

        command: ["python", "main_dispensa.py"]

        depends_on:
            database:
                condition: service_healthy

    backend:
        build:
            context: ./back_end
            dockerfile: Dockerfile

        container_name: backend_api

        restart: "no"

        env_file:
            -   .env

        command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

        ports:
            -   "8000:8000"

        volumes:
            -   ./back_end:/app

        depends_on:
            database:
                condition: service_healthy

volumes:
    database_data: